[build]
  command = "npx vite build"
  publish = "dist"

[build.environment]
  VITE_SUPABASE_URL = "https://hzgohcnktwbavqspkogm.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6Z29oY25rdHdiYXZxc3Brb2dtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTgzNjczMywiZXhwIjoyMTAxNDEyNzMzfQ.G_8EGkyogRmFZY8MwJyQmZGmaxKs1xFA9lqDc14FZUs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
